services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - '3001:3000'
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      ALLOWED_CROSS_ORIGIN: ${ALLOWED_CROSS_ORIGIN}
      ACCESS_TOKEN: ${ACCESS_TOKEN}
    volumes:
      - .:/app
      - /app/dist
      - /mnt/d/image_storage:/app/temp/image_storage # This is the direct mount
    develop:
      watch:
        - path: ./package.json
          action: sync
          target: /app/package.json
        - path: ./package-lock.json
          action: sync
          target: /app/package-lock.json
        - path: ./src
          action: sync
          target: /app/src
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    command: npm run start:dev
