name: Local Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "ALLOWED_CROSS_ORIGIN=${{ vars.ALLOWED_CROSS_ORIGIN}}" > .env
          echo "ACCESS_TOKEN=${{ secrets.ACCESS_TOKEN }}" >> .env

      - name: Start Docker Containers
        run: |
          npm run up
